/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador_de_petshop;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 828461
 */
public class FormPesquisarAtendimento extends javax.swing.JFrame {
    List<Atendimento> atendimentos = new ArrayList();
    DefaultTableModel tableatendimentos = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        } 
    };
    /**
     * Creates new form FormCadastrar
     */
    public FormPesquisarAtendimento() {
        initComponents();
        //leitura do arquivo Json que armazena as senhas, usuários e respostas de perguntas de segurança
        try {
            JsonReader reader = new JsonReader(new FileReader(System.getProperty("user.home") + "\\Desktop\\Atendimentos.json"));
            
            reader.beginArray();
            while(reader.hasNext()){
                Atendimento atd = new Gson().fromJson(reader,Atendimento.class);
                atendimentos.add(atd);
            }
        } catch (Exception e) {
            System.out.println("ERRO: "+e.getMessage());
            
        }
        configurarListarAtendimentos();
    }

    void preencherTabela(){
        if(tableatendimentos.getColumnCount() == 0){
            tableatendimentos.addColumn("Cliente");
            tableatendimentos.addColumn("Data");
            tableatendimentos.addColumn("Categoria");
            tableatendimentos.addColumn("Valor");
        }
        
        for (Atendimento atendimento : atendimentos) {
            tableatendimentos.addRow(new Object[]{atendimento.getCliente(),atendimento.getData(),atendimento.getCategoria(),atendimento.getValor()});
        }
        tblAtendimentos.setModel(tableatendimentos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtendimentos = new javax.swing.JTable();
        txtPesquisaAtendimento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAtendimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAtendimentos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblAtendimentos);

        txtPesquisaAtendimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pesquisar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtPesquisaAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisaAtendimento)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int i = atendimentos.size()-1;
        List<Atendimento> pesquisar = new ArrayList();
        if(tableatendimentos.getRowCount() != 0){
            for(int u = i;u >= 0;u--){
                tableatendimentos.removeRow(u);
            }
        }else if(tableatendimentos.getRowCount() == 0){
            preencherTabela();
        }
        
        for(Atendimento atdm : atendimentos){
            if(txtPesquisaAtendimento.getText().isEmpty()){
                pesquisar.add(atdm);
            }else if(atdm.getCliente().toString().equals(txtPesquisaAtendimento.getText().toString())|| atdm.getData().toString().equals(txtPesquisaAtendimento.getText().toString())){
                pesquisar.add(atdm);
            }
        }
        txtPesquisaAtendimento.setText("");
        for (Atendimento atendimento : pesquisar) {
            tableatendimentos.addRow(new Object[]{atendimento.getCliente(),atendimento.getData(),atendimento.getCategoria(),atendimento.getValor()});
        }
        tblAtendimentos.setModel(tableatendimentos);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesquisarAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAtendimentos;
    private javax.swing.JTextField txtPesquisaAtendimento;
    // End of variables declaration//GEN-END:variables
    
    public void configurarListarAtendimentos(){
        txtPesquisaAtendimento.setToolTipText("Digite a data ou o nome desejado!");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //posicionamento do formulario
        this.setLocationRelativeTo(null);
        //redimensionamento
        this.setResizable(false);
        
        this.setTitle("Atendimentos cadastrados");
        
        preencherTabela();
    }
}
