/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador_de_petshop;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 828461
 */
public class FormListarClientes extends javax.swing.JFrame {
    List<Cliente> clientes = new ArrayList();
    /**
     * Creates new form FormCadastrar
     */
    public FormListarClientes() {
        initComponents();
        //leitura do arquivo Json que armazena as senhas, usuários e respostas de perguntas de segurança
        try {
            JsonReader reader = new JsonReader(new FileReader(System.getProperty("user.home") + "\\Desktop\\Clientes.json"));
            
            reader.beginArray();
            while(reader.hasNext()){
                Cliente cli = new Gson().fromJson(reader,Cliente.class);
                clientes.add(cli);
            }
        } catch (Exception e) {
            System.out.println("ERRO: "+e.getMessage());
            
        }
        configurarListarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        
        int lines = tblClientes.getSelectedRow();
        FormCadastrarCliente alterar = new FormCadastrarCliente(
            tblClientes.getValueAt(lines,0).toString(),
            tblClientes.getValueAt(lines,1).toString(),
            tblClientes.getValueAt(lines,2).toString(),
            tblClientes.getValueAt(lines,3).toString(),
            tblClientes.getValueAt(lines,4).toString());
        alterar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
    
    public void configurarListarClientes(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //posicionamento do formulario
        this.setLocationRelativeTo(null);
        //redimensionamento
        this.setResizable(false);
        this.setTitle("Clientes cadastrados");
        
        DefaultTableModel tableclientes = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                } 
        };
        tableclientes.addColumn("Nome");
        tableclientes.addColumn("CPF");
        tableclientes.addColumn("Celular");
        tableclientes.addColumn("Email");
        tableclientes.addColumn("Endereço");
        
        
        for (Cliente cliente : clientes) {
            tableclientes.addRow(new Object[]{cliente.getNome(),cliente.getCPF(),cliente.getCel(),cliente.getEmail(),cliente.getEndereco()});
        }
        tblClientes.setModel(tableclientes);
    }
}
