/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo4;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 828461
 */
public class FormCadastroCliente extends javax.swing.JFrame {
    
    //java.util.List;
    private List<Cliente> dados;
    
    /**
     * Creates new form FormCadastroCliente
     */
    public FormCadastroCliente() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPrincipal = new javax.swing.JTabbedPane();
        tabCadastrar = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEscolaridade = new javax.swing.JLabel();
        lblProfissao = new javax.swing.JLabel();
        lblTelefoneFixo = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        cbxEscolaridade = new javax.swing.JComboBox<>();
        txtTelefone = new javax.swing.JTextField();
        txtTelefoneCelular = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProfissao = new javax.swing.JList<>();
        tabPesquisar = new javax.swing.JPanel();
        lblNome1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        tabGerenciar = new javax.swing.JPanel();
        btnExportar = new javax.swing.JButton();
        btnImportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setText("Id");

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        lblSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSexo.setText("Sexo");

        lblEscolaridade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEscolaridade.setText("Esolaridade");

        lblProfissao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProfissao.setText("Profissão");

        lblTelefoneFixo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefoneFixo.setText("Telefone Fixo");

        cbxSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoActionPerformed(evt);
            }
        });

        cbxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEscolaridadeActionPerformed(evt);
            }
        });

        lblCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCelular.setText("Telefone Celular");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lstProfissao.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProfissao);

        javax.swing.GroupLayout tabCadastrarLayout = new javax.swing.GroupLayout(tabCadastrar);
        tabCadastrar.setLayout(tabCadastrarLayout);
        tabCadastrarLayout.setHorizontalGroup(
            tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNovo)
                    .addGroup(tabCadastrarLayout.createSequentialGroup()
                        .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfissao)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSexo))
                        .addGap(11, 11, 11)
                        .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEscolaridade)
                            .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefoneFixo)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabCadastrarLayout.createSequentialGroup()
                        .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(txtNome)))
                    .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalvar)
                        .addGroup(tabCadastrarLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCelular)
                                .addComponent(lblEmail)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabCadastrarLayout.setVerticalGroup(
            tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(lblEscolaridade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfissao)
                    .addComponent(lblTelefoneFixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabCadastrarLayout.createSequentialGroup()
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        tabPrincipal.addTab("Cadastrar", new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_cadastrar.png")), tabCadastrar); // NOI18N

        lblNome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome1.setText("Pesquisa por nome");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        javax.swing.GroupLayout tabPesquisarLayout = new javax.swing.GroupLayout(tabPesquisar);
        tabPesquisar.setLayout(tabPesquisarLayout);
        tabPesquisarLayout.setHorizontalGroup(
            tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPesquisarLayout.createSequentialGroup()
                        .addGroup(tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome1)
                            .addComponent(txtNome1))
                        .addGap(148, 148, 148))
                    .addGroup(tabPesquisarLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabPesquisarLayout.setVerticalGroup(
            tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPrincipal.addTab("Pesquisar", new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_pesquisar.png")), tabPesquisar); // NOI18N

        btnExportar.setText("exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnImportar.setText("importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabGerenciarLayout = new javax.swing.GroupLayout(tabGerenciar);
        tabGerenciar.setLayout(tabGerenciarLayout);
        tabGerenciarLayout.setHorizontalGroup(
            tabGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGerenciarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tabGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnImportar)
                    .addComponent(btnExportar))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        tabGerenciarLayout.setVerticalGroup(
            tabGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGerenciarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnExportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportar)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Gerenciar", new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_gerenciar.png")), tabGerenciar); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        //Adicionar dados na tabela
        DefaultTableModel m = (DefaultTableModel)tblClientes.getModel();
        int lin = 0;
        if(txtId.getText().isEmpty()){ 
            //adicionar
            m.addRow(new Object[]{            
                m.getRowCount()+ 1,
                txtNome.getText(),
                cbxSexo.getSelectedItem(),
                cbxEscolaridade.getSelectedItem(),
                lstProfissao.getSelectedValue(),
                txtTelefone.getText(),
                txtTelefoneCelular.getText(),
                txtEmail.getText()
            });
            lin = m.getRowCount()-1;
        }else{
            //alterar
            while(!m.getValueAt(lin,0).toString().equals(txtId.getText())){
                lin++;
            }
            m.setValueAt(txtNome.getText(), lin, 1);
            m.setValueAt(cbxSexo.getSelectedItem(), lin, 2);
            m.setValueAt(cbxEscolaridade.getSelectedItem(), lin, 3);
            m.setValueAt(lstProfissao.getSelectedValue(), lin, 4);
            m.setValueAt(txtTelefone.getText(), lin, 5);
            m.setValueAt(txtTelefoneCelular.getText(), lin, 6);
            m.setValueAt(txtEmail.getText(), lin, 7);
        }
        tblClientes.setModel(m);
        tabPrincipal.setSelectedIndex(1);
        JOptionPane.showMessageDialog(null,"Operação Realizada com sucesso!");
        
        txtNome.setText("");
        cbxSexo.setSelectedIndex(0);
        cbxEscolaridade.setSelectedIndex(0);
        lstProfissao.setSelectedIndex(0);
        txtTelefone.setText("");
        txtTelefoneCelular.setText("");
        txtEmail.setText("");
        
        //adicionar dados à lista dinâmica
        Cliente cli = new Cliente(
            m.getValueAt(lin, 0) .toString(),
            m.getValueAt(lin, 1) .toString(),
            m.getValueAt(lin, 2) .toString(),
            m.getValueAt(lin, 3) .toString(),
            m.getValueAt(lin, 4) .toString(),
            m.getValueAt(lin, 5) .toString(),
            m.getValueAt(lin, 6) .toString(),
            m.getValueAt(lin, 7) .toString()
        );
        
        if(dados.size() < m.getRowCount()){
           dados.add(cli);//adicionar um novo
        }else{
           dados.set(lin,cli);//alterar 
        }
           
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        
        int lin = tblClientes.getSelectedRow();
        if(lin >= 0){
            txtId.setText(tblClientes.getValueAt(lin,0).toString());
            txtNome.setText(tblClientes.getValueAt(lin, 1).toString());
            cbxSexo.setSelectedItem(tblClientes.getValueAt(lin,2));
            cbxEscolaridade.setSelectedItem(tblClientes.getValueAt(lin,3));
            lstProfissao.setSelectedValue(tblClientes.getValueAt(lin,4),true);
            txtTelefone.setText(tblClientes.getValueAt(lin,5).toString());
            txtTelefoneCelular.setText(tblClientes.getValueAt(lin,6).toString());
            txtEmail.setText(tblClientes.getValueAt(lin,7).toString());
                     
            tabPrincipal.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtId.setText("");
        txtNome.setText("");
        cbxSexo.setSelectedIndex(0);
        cbxEscolaridade.setSelectedIndex(0);
        lstProfissao.setSelectedIndex(0);
        txtTelefoneCelular.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtNome.requestFocus();
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        
        try{
            JsonWriter writer = new JsonWriter(new FileWriter(System.getProperty("user.home") + "\\Desktop\\Dados.json"));
            
            writer.beginArray();
            for (Cliente cli: dados) {
                new Gson().toJson(cli, Cliente.class,writer);
            }
            writer.endArray();
            writer.close();
            
        }catch(Exception e){
            System.out.println("ERRO: "+ e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        
        try {
            JsonReader reader = new JsonReader(new FileReader(System.getProperty("user.home") + "\\Desktop\\Dados.json"));
            
            configurarTabela();
            DefaultTableModel m = (DefaultTableModel)
                tblClientes.getModel();
            
            dados = new ArrayList<>();
            reader.beginArray();
            while(reader.hasNext()){
                Cliente cli = new Gson().fromJson(reader,Cliente.class);
                dados.add(cli);
                
                m.addRow(new Object[]{
                    cli.getId(),cli.getNome(),cli.getSexo(),
                    cli.getEscolaridade(),cli.getProfissao(),
                    cli.getTelefone(),cli.getTelefonecelular(),
                    cli.getEmail()
                });
            }
        } catch (Exception e) {
            System.out.println("ERRO: "+e.getMessage());
        }
    }//GEN-LAST:event_btnImportarActionPerformed

    private void cbxEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEscolaridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEscolaridadeActionPerformed

    private void cbxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxEscolaridade;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblProfissao;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefoneFixo;
    private javax.swing.JList<String> lstProfissao;
    private javax.swing.JPanel tabCadastrar;
    private javax.swing.JPanel tabGerenciar;
    private javax.swing.JPanel tabPesquisar;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefoneCelular;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario(){
        this.setTitle("Cadastro de Clientes");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        //iniciar com a guia cadastrar selecionada
        tabPrincipal.setSelectedIndex(0);
        
        preencherComboSexo();
        preencherComboEscolaridade();
        preencherListaProfissoes();
        configurarTabela();
        txtId.setEditable(false);
        
        //criar a lista dinâmica de clientes
        dados = new ArrayList<>();
    }
    
    void preencherComboSexo(){
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        m.addElement("Masculino");
        m.addElement("Feminino");
        cbxSexo.setModel(m);
    }   
    
    void preencherComboEscolaridade(){
        String escolaridade[] = new String[]{"Ensino Fundamental","Ensino médio","Ensino Superior","Especialização","Mestrado","Doutorado"};
        DefaultComboBoxModel m = new DefaultComboBoxModel(escolaridade);
        cbxEscolaridade.setModel(m);
        
        //definir o Ensino Superior como selecionado:
        cbxEscolaridade.setSelectedIndex(2);
    } 
    
    void preencherListaProfissoes(){
        String profissoes[] = new String[]{
	"Astronomia",
	"Banco de Dados",
	"Ciência da Computação",
	"Ciência e Tecnologia",
	"Computação",
	"Estatística",
	"Física",
	"Gestão da Tecnologia da Informação",
	"Informática Biomédica",
	"Matemática",
	"Nanotecnologia",
	"Química",
	"Redes de Computadores",
	"Segurança da Informação",
	"Sistemas de Informação",
	"Sistemas para Internet","Engenharia da Computação"
        };
        
        //ordenação 
        List<String> lista = new ArrayList<>();
        for (String s : profissoes) {
            lista.add(s);
        }
        Collections.sort(lista);
        
        DefaultListModel m = new DefaultListModel();
        for (String u : lista){
            m.addElement(u);
        }
        lstProfissao.setModel(m);
            
        //Definir o modo de múltiplas seleções
        lstProfissao.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        }
        
        /*Definir o modo de seleção única
        lstProfissao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }*/
        
        private void configurarTabela(){
            DefaultTableModel m = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row, int column){

                    return false;
                } 
            };
        
            m.addColumn("Id");
            m.addColumn("Nome");
            m.addColumn("Sexo");
            m.addColumn("Escolaridade");
            m.addColumn("Profissão");
            m.addColumn("Tel.Fixo");
            m.addColumn("Tel.Celular");
            m.addColumn("Email");
            tblClientes.setModel(m);
        }
        
}
