/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo3;

import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author 828461
 */
public class FormPizzariaDoJoao extends javax.swing.JFrame {

    /**
     * Creates new form FormPizzariaDoJoao
     */
    public FormPizzariaDoJoao() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTamanho = new javax.swing.JLabel();
        rdbPequena = new javax.swing.JRadioButton();
        rdbGrande = new javax.swing.JRadioButton();
        rdbExtraGrande = new javax.swing.JRadioButton();
        rdbMedia = new javax.swing.JRadioButton();
        lblCabecalho = new javax.swing.JLabel();
        lblIngredientes = new javax.swing.JLabel();
        chkMolho = new javax.swing.JCheckBox();
        chkQueijo = new javax.swing.JCheckBox();
        chkCebola = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkFrango = new javax.swing.JCheckBox();
        chkPresunto = new javax.swing.JCheckBox();
        chkCalabresa = new javax.swing.JCheckBox();
        chkPalmito = new javax.swing.JCheckBox();
        chkAzeitona = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTamanho.setText("Tamanho");

        rdbPequena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbPequena.setText("Pequena");

        rdbGrande.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbGrande.setText("Grande");

        rdbExtraGrande.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbExtraGrande.setText("Extra Grande");

        rdbMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbMedia.setText("Media");

        lblCabecalho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCabecalho.setText("Pizzaria do João");

        lblIngredientes.setText("Ingredientes");

        chkMolho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkMolho.setText("Molho");
        chkMolho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMolhoActionPerformed(evt);
            }
        });

        chkQueijo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkQueijo.setText("Queijo");

        chkCebola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkCebola.setText("Cebola");

        chkBacon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkBacon.setText("Bacon");

        chkFrango.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkFrango.setText("Frango");

        chkPresunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkPresunto.setText("Presunto");

        chkCalabresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkCalabresa.setText("Calabresa");

        chkPalmito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkPalmito.setText("Palmito");

        chkAzeitona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkAzeitona.setText("Azeitona");

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular preço");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pizza.jpg"))); // NOI18N
        jLabel4.setText("imagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbPequena)
                                .addGap(18, 18, 18)
                                .addComponent(rdbMedia)
                                .addGap(16, 16, 16)
                                .addComponent(rdbGrande)
                                .addGap(18, 18, 18)
                                .addComponent(rdbExtraGrande)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCabecalho))
                            .addComponent(lblTamanho)
                            .addComponent(lblIngredientes)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkMolho)
                                    .addComponent(chkQueijo)
                                    .addComponent(chkCebola))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBacon)
                                    .addComponent(chkFrango)
                                    .addComponent(chkPresunto))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCalabresa)
                                    .addComponent(chkPalmito)
                                    .addComponent(chkAzeitona))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCabecalho)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblTamanho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbPequena)
                    .addComponent(rdbMedia)
                    .addComponent(rdbGrande)
                    .addComponent(rdbExtraGrande))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngredientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkMolho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkQueijo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCebola))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkBacon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFrango)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPresunto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCalabresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPalmito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkAzeitona)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double preco = 0;
        
        if(rdbPequena.isSelected()){
            preco = 30;
        }else if(rdbMedia.isSelected()){
            preco = 40;
        }else if(rdbGrande.isSelected()){
            preco = 50;
        }else if(rdbExtraGrande.isSelected()){
            preco = 60;
        }
        
        if(chkMolho.isSelected()){
            preco += 2.50;
        }
        
        //operador ternário
        preco += chkQueijo.isSelected()? 6 : 0;
        preco += chkCebola.isSelected()? 2 : 0;
        preco += chkBacon.isSelected()? 5 : 0;
        preco += chkFrango.isSelected()? 6 : 0;
        preco += chkPresunto.isSelected()? 2 : 0;
        preco += chkCalabresa.isSelected()? 4 : 0;
        preco += chkPalmito.isSelected()? 8 : 0;
        preco += chkAzeitona.isSelected()? 3 : 0;
        
        JOptionPane.showMessageDialog(null,String.format("Preço: R$ %.2f",preco));
        
        //limpa as seleções dos JCheckBox
        for (Component comp : getContentPane().getComponents()) {
            if(comp instanceof JCheckBox){
                JCheckBox chk = (JCheckBox)comp;
                chk.setSelected(false);
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void chkMolhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMolhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMolhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPizzariaDoJoao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPizzariaDoJoao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPizzariaDoJoao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPizzariaDoJoao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPizzariaDoJoao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JCheckBox chkAzeitona;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkCalabresa;
    private javax.swing.JCheckBox chkCebola;
    private javax.swing.JCheckBox chkFrango;
    private javax.swing.JCheckBox chkMolho;
    private javax.swing.JCheckBox chkPalmito;
    private javax.swing.JCheckBox chkPresunto;
    private javax.swing.JCheckBox chkQueijo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JRadioButton rdbExtraGrande;
    private javax.swing.JRadioButton rdbGrande;
    private javax.swing.JRadioButton rdbMedia;
    private javax.swing.JRadioButton rdbPequena;
    // End of variables declaration//GEN-END:variables

private void configurarFormulario(){
    this.setTitle("Pizzaria do João");
    this.setResizable(false);
    this.setLocationRelativeTo(null);
    
    //Definir SELEÇÃO EXCLUSIVA nos RadioButtons
    ButtonGroup bg = new ButtonGroup();
    bg.add(rdbPequena);
    bg.add(rdbMedia);
    bg.add(rdbGrande);
    bg.add(rdbExtraGrande);
    rdbGrande.setSelected(true);
    
}


}
